# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4292dd1c9ff066e1487ab97586b5a6db7ee59c83f91553395a2a816104e646a8d8bd126739e37975993087d7821c134f5d44e5377a2177bb1f4467eb65cea652

test:
  secret_key_base: f625c0ec07e6a3e510d936de98543fcbeb0479aeeb3fb8c5957c092f3a784e8e20c5e5ba72cd380b3befffe8e6cfd9405e912793e3f0f29986d88b10d510a360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
